using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SecureOps.Models;

namespace SecureOps.Services
{
    public class PdfService
    {
        private readonly string _incidentImageRoot;

        public PdfService(IWebHostEnvironment env)
        {
            // e.g., wwwroot/IncidentImages
            _incidentImageRoot = Path.Combine(env.WebRootPath, "photos");
        }  // 🧾 Incident PDF generator
        public byte[] GenerateIncidentReport(Incident incident)
        {
            var folderPath = Path.Combine(_incidentImageRoot, incident.Id.ToString());
            var imageFiles = Directory.Exists(folderPath)
                ? Directory.GetFiles(folderPath)
                : Array.Empty<string>();

            var pdf = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(40);
                    page.Size(PageSizes.A4);

                    page.Header()
                        .Text("Incident Report")
                        .FontSize(22)
                        .Bold()
                        .AlignCenter();

                    page.Content().Column(col =>
                    {
                        col.Spacing(10);

                        col.Item().Text($"Title: {incident.Title}").FontSize(14).Bold();
                        col.Item().Text($"Reported By: {incident.Employee?.FullName ?? "N/A"}");
                        col.Item().Text($"Reported At: {incident.ReportedAt:dd/MM/yyyy hh:mm tt}");
                        col.Item().Text($"Status: {incident.Status}");
                        col.Item().Text($"Description: {incident.Description}");

                        col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                        // 🖼 Add images section
                        if (imageFiles.Length > 0)
                        {
                            col.Item().Text("Attached Photos:").FontSize(14).Bold().Underline();

                            // group images 2 per row
                            for (int i = 0; i < imageFiles.Length; i += 2)
                            {
                                var rowImages = imageFiles.Skip(i).Take(2).ToList();

                                col.Item().Row(row =>
                                {
                                    foreach (var imagePath in rowImages)
                                    {
                                        try
                                        {
                                            var imageBytes = File.ReadAllBytes(imagePath);
                                            row.RelativeItem(1).Padding(5).Border(1).BorderColor(Colors.Grey.Lighten2)
                                                .Height(200)
                                                .Image(imageBytes)
                                                .FitArea()
                                                .WithCompressionQuality(ImageCompressionQuality.High);
                                        }
                                        catch
                                        {
                                            row.RelativeItem(1)
                                                .Text($"Error loading {Path.GetFileName(imagePath)}")
                                                .FontColor(Colors.Red.Medium)
                                                .AlignCenter();
                                        }
                                    }

                                    // If only one image in the last row, fill the space to keep layout even
                                    if (rowImages.Count == 1)
                                        row.RelativeItem(1).Padding(5);
                                });
                            }
                        }
                        else
                        {
                            col.Item().Text("No photos available.").Italic().FontSize(11).FontColor(Colors.Grey.Medium);
                        }

                        col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                        col.Item().Text("Generated by SecureOps").FontSize(10).Italic().AlignRight();
                    });
                });
            });

            return pdf.GeneratePdf();
        }
        public byte[] GenerateSafetyTaskReport(SafetyTask task)
        {
            var pdf = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(40);
                    page.Size(PageSizes.A4);

                    page.Header()
                        .Text("Safety Task Report")
                        .FontSize(22)
                        .Bold()
                        .AlignCenter();

                    page.Content()
                        .Column(col =>
                        {
                            col.Spacing(10);

                            col.Item().Text($"Task Title: {task.Title}");
                            col.Item().Text($"Assigned To: {task.Employee?.FullName}");
                            col.Item().Text($"Due Date: {task.DueDate:d}");
                            col.Item().Text($"Description: {task.Description}");
                            col.Item().Text($"Status: {(task.Status.Equals("Done") ? "Done" : "Pending")}");

                            col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                            col.Item().Text("Generated by SecureOps").FontSize(10).Italic().AlignRight();
                        });
                });
            });

            return pdf.GeneratePdf();
        }
    }
}
